/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel_agency;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane; 

/**
 *
 * @author Dell
 */
public class signup2 extends javax.swing.JFrame {
Connection con=null; 
int userid;
double count=0;
    /**
     * Creates new form signup2
     */
    public signup2() {
        initComponents();
    }
    public signup2(int id) {
        initComponents();
        userid=id;
    try
        {
            JOptionPane.showMessageDialog(null, ""+count);
         Class.forName("java.sql.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost/agencytravel","root","");
         String query="select * from members where membership_id="+userid+" ;";
         JOptionPane.showMessageDialog(null, "Final Query :"+query);
         Statement stmt=con.createStatement();
         ResultSet rs=stmt.executeQuery(query);
            if(rs.next()) 
            {
                 output.setText("Hello! "+rs.getString("name")+"\n"
                         + "Welcome To our Travel Agency"
                         + "Your User Name is "+rs.getString("Username")+"\n"
                 + "Your Membership id is "+rs.getString("membership_id")+"\n"
                         + "Your Wallet balance is "+rs.getString("wallet_amt")+"\n"
                                 + "your address is "+rs.getString("address")+"\n"
                                         + "Your Mobile Number is "+rs.getString("mobile_no"));
            }


         con.close();
        }
        catch(Exception e){
     JOptionPane.showMessageDialog(null, e); 
    } 
        
    }
    public signup2(int userid,String a,double c) {
        initComponents();
        count=c;
         try
        {
            JOptionPane.showMessageDialog(null, ""+count);
         Class.forName("java.sql.Driver");
         con=DriverManager.getConnection("jdbc:mysql://localhost/agencytravel","root","");
         String query="select * from staffmembers where staff_id="+userid+";";
         JOptionPane.showMessageDialog(null, "Final Query :"+query);
         Statement stmt=con.createStatement();
         ResultSet rs=stmt.executeQuery(query);
            if(rs.next()) 
            {
                 output.setText("Hello! "+rs.getString("name")+"\n"
                         + "Welcome To our Travel Agency"
                         + "Your User Name is "+rs.getString("Username")+"\n"
                 + "Your Staff id is "+rs.getString("staff_id")+"\n"
                         + "Your Login Passsword is "+rs.getString("password")+"\n"
                         + "Your Working Status is "+rs.getString("staff_working_status")+"\n"
                                 + "your address is "+rs.getString("address")+"\n"
                                         + "Your Mobile Number is "+rs.getString("mobile_no"));
            }


         con.close();
        }
        catch(Exception e){
     JOptionPane.showMessageDialog(null, e); 
    } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        output.setEditable(false);
        output.setColumns(20);
        output.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("Login For Further Proceedings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(count ==0)
        {
        login_page obj=new login_page();
        obj.setVisible(true);
        this.setVisible(false);
        }
        else 
            if(count==5)
            {
                staff_main_page obj=new staff_main_page();
                obj.setVisible(true);
                this.setVisible(false);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
